server:
  port: 8761

spring:
  application:
    name: discovery-service

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    registryFetchIntervalSeconds: 60
  instance:
    leaseRenewalIntervalInSeconds: 30
  server:
    enableSelfPreservation: true
    renewalPercentThreshold: 90
